### ISSUE TITLE
Will flowPloidy work on mammalian samples?

### ISSUE THREAD

**Issue by bmreilly** [plantarum/flowPloidy#1] opened 2018-01-17 03:30 UTC
Hi - I am really impressed with the ease of use of this tool, so thanks for your hard work! My present issue is that I am having some issues when using flowPloidy to analyze human cancer cell lines DNA content (measured via propidium iodide fluorescence).  I'm a bit confused about how the model finds the location of the G2 peak, because I am not able to generate a model that accurately picks this peaks from my data, although it does come close.  I've attached an image showing that the G1 peak is correctly modeled in both height and location, but the S phase and G2 peak in the model seem to be shifted to the right.  Do you have any suggestions on how I might better model my data? Or is this the expected behavior? Thanks! 

![image](https://user-images.githubusercontent.com/7952375/35024137-b994d636-faf2-11e7-9552-e0d79ca1bc7a.png)

**Comment by plantarum** [comment] 2018-01-17 04:07
That's expected behaviour, but it's also incorrect in this case. I have set limits for linearity at 1.9 and 2.1. In your case your G2 peak is less than 1.9 times the size of the G1 peak, so I'm not allowing you to fit your data properly.

I don't have a solid reason for the limits, I just picked something that seemed reasonable for our data. This will be easy to fix, I'll just decrease the lower limit.

My understanding of linearity shifts is that local conditions, like temperature and pressure, and the condition of the cytometer, and even how long the cytometer has been running, can all influence how far off of the expected ratio of 2 your G2 peak is. So it's not unusual for it to vary. I would be interested in knowing more about the physics of this.

I should be able to push a fix to the dev branch by the end of the week. Thanks for your interest!

**Comment by bmreilly** [comment] 2018-01-17 17:58
I thought it might have something to do with the linearity parameter, I'm glad you have an easy fix for this!

I have another question:  I see in the output of `flowHist` that there is a value `counts` which counts the number of cells in each G1 sample peak (A/B) in the data.  I was wondering if there was any way to get the counts for the G2 and S regions of the histogram also since these peaks/regions seem to be modeled in the same fashion as the G1 peak.  I'm mainly interested in determining the % of cells in each phase of the cell cycle, so counts for the modeled peaks would work perfectly (it would essentially be the area under the modeled curve for each population, right?).

I know that many researchers at my institution would be interested in a simple R based method for modeling (and counting) cell cycle populations. Right now most people use FlowJo to model and quantify cell cycle populations, but because FlowJo is so expensive we share a single FlowJo license between ~30-40 people in my lab floor, and this is a huge pain. Your package could be a big hit!

Thanks again!

**Comment by plantarum** [comment] 2018-01-17 18:27
The G2 peak counts will be easy. I only excluded them because we don't use them in our work, but the code is identical as what I've used for the G1 peaks, just swapping out the appropriate parameter estimates.

The S-phase should be doable too, the function I use for that component is pretty simple. 

I can't do the debris curves, and so the total model, as the debris components are a little funky to compute. The way I've coded them, I can't use R's built in `integrate` function (to get the area under the curve), so I'd have build something from scratch. That would require a bit of work. 

I'll put the rest on the todo list!

**Comment by bmreilly** [comment] 2018-01-17 18:45
I'm glad it won't be too hard to implement the G2 and S population counts, that is good news!  In terms of the debris: Actually I think that with your built in interactive gating it wouldn't be too bad to simply exclude the debris curve for this purpose. I did some tests, and most of the debris I would be concerned with were easily gated out using the interactive method.

Please let me know if I can help you at all with this implementation - I'd be happy to help any way I can.

**Comment by plantarum** [comment] 2018-01-17 21:38
I just pushed a batch of commits, including relaxing the limits on linearity. You'll have to install directly from GitHub, this won't show up in BioConductor until the next release in April. There are instructions on the flowPloidy readme (which is the 'homepage' for the github repo).

Let me know how this works for your sample! The model should fit no problem on such clean data, and the RCS value should drop to a more usual value once the peaks are properly placed.

I'll continue on to the G2 and S-phase counts later in the week.

**Comment by bmreilly** [comment] 2018-01-17 23:02
I just installed the new version and tested it out on my data.  It definitely fits much better after you relaxed the linearity range, however the RCS values are still a bit high (8.8).  I would consider this fit to be acceptable, but if you have any ideas on how to improve on that RCS I would be happy to test it out.  Also if you would  like I can send you an FCS file with data.
Thanks for updating it so quickly!

P.S.
Here is an image of the fit with the updated package:

![image](https://user-images.githubusercontent.com/7952375/35071755-c19b17e2-fb96-11e7-9c49-8b1b83c7987e.png)

**Comment by bmreilly** [comment] 2018-01-18 19:15
One more thing - For some reason the model cannot re-fit correctly if I set a gate.  See images below, first image is without a gate, second image is after setting a gate on FL2-H vs. FL2-W.  Its not a huge issue for my experiment, as gating is not totally necessary, but I thought you should know about this behavior.  Thanks!

![image](https://user-images.githubusercontent.com/7952375/35116475-75c59bb2-fc40-11e7-95f9-1661a6d84f5a.png)


![image](https://user-images.githubusercontent.com/7952375/35116424-4003c1c0-fc40-11e7-9bbf-3a1b4cc9cbe7.png)

**Comment by plantarum** [comment] 2018-01-19 18:22
I think I know where these problems are coming from, but I'm not sure of the best way to address them. Can you send me your FCS file so I can take a closer look?

**Comment by bmreilly** [comment] 2018-01-19 20:24
Sure, here is an example FCS file.
[sample.001.fcs.gz](https://github.com/plantarum/flowPloidy/files/1647839/sample.001.fcs.gz)

**Comment by plantarum** [comment] 2018-01-19 23:42
I just pushed another batch of commits, the largest of which implements cell counts for G2 peaks and S-phase. I've tested it enough to know that it doesn't crash anything, but I haven't looked at the values to confirm that they are sensible. Take a look and tell me what you think.

The easiest way to see the values is probably tabulateFlowHist(), which will work for single FlowHist objects, or lists of objects. You can also see them via the fhCounts() function, which only works for single FlowHist objects.

**Comment by plantarum** [comment] 2018-01-20 00:00
Is the sample file you sent me the same one that you have provided images of? I'm getting a G1 peak around 68, or 100, depending on the channel I pick, and your images show a peak at 78. If we're looking at the same data I would expect the results to differ by at most 1.0, and usually less than that.

**Comment by bmreilly** [comment] 2018-01-20 00:41
Hi, I've just downloaded the new version and tested on the sample I sent you.  The results look the same as before with a peak at 78  for the G1 peak (on FL2). Here is the image: 

![image](https://user-images.githubusercontent.com/7952375/35177569-7d4337c8-fd35-11e7-9d6f-d140b7501020.png)

In tabulateFlowHist() is it CountsA, CountsA2, and CountsSA for G1,G2, and S, respectively? 

If so, it looks reasonable at first glance, I'll look in a bit more detail and get back to you.  Also - not sure if intentional, but in the output of tabulateFlowHist()  `countsSA` is a list, whereas the other variables are all vectors .

**Comment by plantarum** [comment] 2018-02-12 18:46
Yes, the counts are labelled as you thought. I've just pushed a commit to fix the issue with `countsSA` (and `countsSB` and `countsSC`) being lists instead of numeric values.

I still can't reproduce your histogram with the file you posted. For example:

```
brian <- FlowHist("~/research/flow/sample.001.fcs", channel = "FL2.H",
                  samples = 1)
```

Gives me (after correcting the initial peak estimate):

![fl2h](https://user-images.githubusercontent.com/5727138/36113136-db33c9b6-0ff9-11e8-8f58-0cbcc2a8f5c2.png)

And if I use `FL2.A`:

![fl2a](https://user-images.githubusercontent.com/5727138/36113220-1cba9d4c-0ffa-11e8-8768-ea6f1d290437.png)

Neither one is close to 78.3. Can you tell me what the following code returns when you use the fcs file you posted please?

```
brian <- FlowHist("PATH/TO/sample.001.fcs", channel = "FL2.A",
                  samples = 1)

library(digest)
digest(brian@histData$intensity, "md5")

brian@raw@description$`$DATE`
brian@raw@description$`$BTIM`
brian@raw@description$`FILE GUID`
```

**Comment by plantarum** [comment] 2018-03-08 15:19
Have you had a chance to check on my previous comment? I'd like to sort this out if possible!

**Comment by bmreilly** [comment] 2018-03-09 00:56
Hey - sorry I got busy when the last one came through and it slipped my mind.

Here is the output of the commands you wanted:
```
> brian = FlowHist(fcsFiles[1], channel = "FL2.H", samples=1)
analyzing sample.001
> library(digest)
> digest(brian@histData$intensity, "md5")
[1] "c331e268ccf207f793351e5b43751159"
> brian@raw@description$`$DATE`
[1] "12-Jan-18"
> brian@raw@description$`$BTIM`
[1] "16:17:03"
> brian@raw@description$`FILE GUID`
[1] "14E076AC-F7F7-11E7-B306-001124882388"
```

**Comment by plantarum** [comment] 2018-03-09 15:02
No problem, I've been busy until now anyways!

When I run the commands above on the file you uploaded earlier, I get:

    > brian <- FlowHist("~/research/flow/sample.001.fcs", channel = "FL2.A",
    +                   samples = 1) 
    analyzing sample.001.fcs
        *** Model Fit Needs Attention: sample.001.fcs ***
    > library(digest)
    > digest(brian@histData$intensity, "md5")
    [1] "f0724874dd1beeb6bb5e20fac8e3de5e"
    > brian@raw@description$`$DATE`
    [1] "17-Jan-18"
    > brian@raw@description$`$BTIM`
    [1] "17:11:47"
    > brian@raw@description$`FILE GUID`
    [1] "8E581367-FBEC-11E7-AE75-001124882388"

This means we're not looking at the same data! Your file was run on 12-Jan-18, mine was run on 17-Jan-18.

Can you repost the data you referred to in your comment above please? https://github.com/plantarum/flowPloidy/issues/1#issuecomment-358751632

**Comment by plantarum** [comment] 2023-03-17 14:51
Closing due to lack of info. Send me a note if you want to revisit this.

**Closed as completed by plantarum** 2023-03-17 14:51 UTC
Labels: bug, enhancement
