### ISSUE TITLE
Problem importing files in development version of flowPloidy

### ISSUE THREAD

**Issue by IrisvdP** [plantarum/flowPloidy#2] opened 2018-07-23 10:42 UTC
Hi, 

Recently I saw that you added a new feature in the development version of flowPloidy to asses endopolyploidy. This would be very useful for my research, as my samples contain not only diploid and tetraploid cells, but also hexaploid and octaploid cells. I want to asses the fraction of polyploid cells in my samples, so I would like to asses every peak like a separate group of cells.
After I installed flowPloidy from the GitHub repository, I tried including the G2 = FALSE argument in the batchFlowHist function, but I get an error: "**PROBLEM: I couldn't import ..... .LMD **The following files failed to load:....LMD". There is no further explanation of why these files do not load. When I don't include the G2 = FALSE argument, I can analyse the same files perfectly with the stable flowPloidy version.

Do you know a way to load my files so I can assess endopolyploidy with the development version?

Thanks for your help.

Iris

**Comment by plantarum** [comment] 2018-07-23 11:41
Hi Iris,

Can you post the file so I can take a look?

Best,

Tyler

**Comment by IrisvdP** [comment] 2018-07-23 14:40
Hi Tyler,

Attached you find two types of files. I zipped them as LMD files are not supported. "A5control" contains 1 sample, whereas "C2cs20minf3" contains 2 samples (you also see a peak there of triploid cells). If you need more information, please let me know.

Iris
[LMDfiles.zip](https://github.com/plantarum/flowPloidy/files/2219727/LMDfiles.zip)

**Comment by plantarum** [comment] 2018-07-30 16:29
I think the problem is that you're using the argument "G2", when it should be "g2". This has confused other people, I may end up changing the argument name to something more obvious before this gets released in October.

The following worked for me:

    irisData <- list.files("../../problems/iris",
                       pattern = "LMD", full.names=TRUE)

    irisBatch <- batchFlowHist(irisData, channel="FL3.Lin", g2 = FALSE)

**Comment by IrisvdP** [comment] 2018-07-31 10:37
Thank you! With the "g2" instead of "G2" it works for me as well. I put in the "G2" argument because that is how it was explained for the development version in the README.md. Thanks again for your help!

**Comment by plantarum** [comment] 2018-08-01 13:51
Shoot, so it did. I've corrected it now. For the release, I may rename it to something more descriptive than `g2`.

**Closed as completed by plantarum** 2018-08-01 13:51 UTC
